services:
  frontend:
    env_file: 
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REPO_URL=${REPO_URL}
    ports:
      - "${NEXTJS_PORT}:3000"
    environment:
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017/${MONGO_DB_NAME}.db?authSource=admin
    restart: always
    depends_on:
      - mongodb
    networks:
      - host

  mongodb:
    env_file: 
      - .env
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    volumes:
      - dbdata:/data/db
    restart: unless-stopped
    networks:
      - host
volumes:
  dbdata:

networks:
  host:
    external: true
