services:
  frontend:
    env_file: 
      - .env
    ports:
      - "${NEXTJS_PORT}:3000"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REPO_URL=${REPO_URL}
    environment:
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@localhost:27017/${MONGO_DB_NAME}.db?authSource=admin
      - HOST:0.0.0.0
      - PORT:${NEXTJS_PORT}
      - NEXTJS_BIND_ADDRESS:0.0.0.0
      - NEXTJS_PUBLIC_SITE_URL:http://127.0.0.1:${NEXTJS_PORT}
    restart: always
    depends_on:
      - mongodb

  mongodb:
    env_file: 
      - .env
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    volumes:
      - dbdata:/data/db
    restart: unless-stopped
volumes:
  dbdata:
